# Generated by Django 4.0.4 on 2022-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslides',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
