# Generated by Django 4.0.4 on 2022-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_blog_homecategories_teammembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='fb_account',
            field=models.URLField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='gl_account',
            field=models.URLField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='tr_account',
            field=models.URLField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='yt_account',
            field=models.URLField(blank=True, max_length=20, null=True),
        ),
    ]
