# Generated by Django 4.0.4 on 2022-06-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_products_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslides',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeslides',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homeslides',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homeslides',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
