# Generated by Django 4.0.4 on 2022-06-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_homeslides_description_en_homeslides_description_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brandcategories',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='brandcategories',
            name='name_uz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_uz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='name_uz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='profession_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='profession_uz',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
