# Generated by Django 4.0.4 on 2022-05-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_products_is_top'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeCategories',
        ),
    ]
